### ISSUE TITLE
【Taro ui 3.0 alpha版】AtInput事件不能被触发

### ISSUE THREAD

**Issue by Blueria** [NervJS/taro-ui#1128]
### Taro UI 版本信息

v3.0.0-alpha.3

### 问题描述

@tarojs/taro版本：3.0.2
nervjs版本：1.5.0
taro-ui版本：3.0.0-alpha.3（注意：不是v2版本）

AtInput组件的onChange事件触发不了，也试了onFocus、onBlur事件，一样没反应

### 复现步骤

直接看代码（代码比较简单）

### 复现代码
```jsx
import Nerv, { Component } from 'nervjs';
import { View, Text } from '@tarojs/components';
import { AtForm, AtInput, AtButton } from 'taro-ui';

// 注意：这里继承的是Nerv.Component
class Index extends Component {
    constructor(props) {
        super(props);
        this.state = {
            phone: '',
            password: '',
        };
    }

    componentWillMount() {}

    componentDidMount() {}

    componentWillUnmount() {}

    componentDidShow() {}

    componentDidHide() {}

    render() {
        return (
            <View>
                <AtForm>
                    <AtInput title='+86' type='phone' value={this.state.phone} placeholder='请输入手机号' onChange={() => { console.log(123) }} />
                    <AtInput title='密码' type='text' value={this.state.password} placeholder='请输入密码' />
                </AtForm>
                <AtButton type='primary' circle>登录</AtButton>
            </View>
        );
    }
}

export default Index;
```

### 报错信息

onChange没有触发，因为console.log没有打印123（另外：密码竟然跟手机号码同步变化:joy::joy::joy:）

![20200709164858](https://user-images.githubusercontent.com/7038130/87018723-38fd3f00-c204-11ea-97f6-056fedd8707a.png)

### 系统信息

```yaml
Taro CLI 3.0.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
```

### 补充信息

无
