### ISSUE TITLE
AtTabs 这个标签页能不能固定在顶部或者自定义固定位置

### ISSUE THREAD

**Issue by EForinaJ** [NervJS/taro-ui#133]
AtTabs 这个标签页组件能不能固定在顶部或者自定义固定位置，有时候大部分的都是固定在导航条顶部的， 我设置绝对定位 就整个都定死了 包括页面 不能拖动了 能不能给个参数固定位置的

**Comment by jimczj** [comment]
要固定顶部的话，可以设置 `position: fixed` 近期会研究看看有没有增加这个参数

**Comment by jimczj** [comment]
要固定顶部的话，可以设置 `position: fixed` 近期会研究看看有没有增加这个参数

**Comment by jimczj** [comment]
可以给 header 加 `position: fixed` 后期将增强这一功能

**Comment by jimczj** [comment]
你好这个需求我觉得，你嵌套一个 scrollView 或给 view 固定高度，`overflow: scroll` 可以解决

**Comment by mrzhouxu** [comment]
嵌套 scrollView 的话，下拉刷新就不能使用了，给 view 固定高度的话，onReachBottom 这个 API 就会有问题了。还是希望可以有一个参数让他固定在顶部，如果设置 position:fixed 的话，就出现不能左右滚动的问题了，希望你们可以排查一下

**Comment by zicjin** [comment]
如何固定高度呢？100vh也不合适啊，因为顶栏有高度

**Comment by w13808604** [comment]
设置了position: fixed，然后包了一个ScrollView仍然解决不了问题啊。AtTabs这个组件为啥会带动整个页面滑动了？

**Comment by GarfieldLucy** [comment]
所以解决方案是啥

**Comment by GarfieldLucy** [comment]
> 你好这个需求我觉得，你嵌套一个 scrollView 或给 view 固定高度，`overflow: scroll` 可以解决

请问现在有解决方案吗

**Comment by my6521** [comment]
请问这个解决了吗？这是要让我们放弃的节奏

**Comment by beilunyang** [comment]
请问有解决方案了吗，AtTabs加ScrollView应该是很常见的场景

**Comment by beilunyang** [comment]
楼上的朋友应该都已经解决了，但还是回答下，方便日后有遇到同样问题的人
```scss
// scss
:global {
  .at-tabs__header {
    position: fixed;
    z-index: 100;
    top: 0;
    left: 0;
  }
}
.orderList {
  box-sizing: border-box;
  height: 100vh;
  padding-top: 86px;
}

```
```javascript
// javascript
<AtTabs>
  <AtTabsPane>
    <ScrollView
     // scroll-y 默认值为false，需要手动设为true，因为这个属性我才百度到的这个issue
      scroll-y     
      className={styles.orderList}
      lowerThreshold={200}
    >
      {list}
    </ScrollView>
  </AtTabsPane>
</AtTabs>
```
```
// 版本
taro: 2.2.2
taro-ui: 2.3.4
```
