### ISSUE TITLE
在H5中，IOS系统下tabbar优先级始终高于ATFloatLayout，安卓下正常

### ISSUE THREAD

**Issue by amusiq** [NervJS/taro-ui#152]
在编译H5后，真机上测试，发现IOS系统下，底部的Tabbar优先级高过ATFloatLayout，导致ATFloatLayout的底部一部分被Tabbar遮住了。尝试设置ATFloatLayout的优先级z-index最高都没作用。

**Comment by SzHeJason** [comment]
这是H5环境的问题？ 小程序是好的吗？

**Comment by SzHeJason** [comment]
你好 我在 本地测试了一下 并没有发现这个问题 所谓的 Tabbar 是指 AtTabBar 这个组件吗

**Comment by SzHeJason** [comment]
这是 taro 的布局影响的 目前 taro 正在重构路由布局 你可以通过在 h5 设置 at-float-layout的高来处理 `height: calc(100% - tabbar)`

**Comment by SzHeJason** [comment]
暂时解决方案 在 app.scss 加上 下面代码
```css
.taro-tabbar__panel {
  transform: translate3d(0, 0, 0);
}
```
