### ISSUE TITLE
微信小程序平台图标库设置按照官方文档以及已有的解决方案都未能解决，还是显示框框

### ISSUE THREAD

**Issue by lynshir** [NervJS/taro-ui#499]
### Taro UI 版本信息

2.0.1

### 问题描述

按照官方文档以及已有的解决方案都未能解决，显示```Failed to load local font resource /fonts/icomoon.ttf?av4s6z-do-not-use-local-path-./app.wxss&15269&7 net::ERR_CACHE_MISS ``` ,引不到字体文件，我看dist文件夹没有把字体文件构建进去，我按照官方文档配置都配置了

### 复现步骤

fonts文件夹未能构建进去dist目录

### 复现代码

config文件，按照官方教程配置的
```
module.exports = {
  env: {
    NODE_ENV: '"development"'
  },
  defineConstants: {},
  // 小程序端专用配置
  weapp: {
    module: {
      postcss: {
        autoprefixer: {
          enable: true
        },
        // 小程序端样式引用本地资源内联配置
        url: {
          enable: true,
          config: {
            limit: 10240 // 文件大小限制
          }
        }
      }
    }
  },
  h5: {}
}
```
src目录下的icon.scss
```css
@font-face {
  font-family: 'icomoon';
  src: url('./fonts/icomoon.eot?av4s6z');
  src: url('./fonts/icomoon.eot?av4s6z#iefix') format('embedded-opentype'),
    url('./fonts/icomoon.ttf?av4s6z') format('truetype'),
    url('./fonts/icomoon.woff?av4s6z') format('woff'),
    url('./fonts/icomoon.svg?av4s6z#icomoon') format('svg');
  font-weight: normal;
  font-style: normal;
}
.icon {
  /* use !important to prevent issues with browser extensions that change fonts */
  font-family: 'icomoon' !important;
  speak: none;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-transform: none;
  line-height: 1;

  /* Better Font Rendering =========== */
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

```
同时在src目录下建立了fonts文件夹，将字体文件放了进去（assets目录也试了），在dist目录没能build进去，所有就引用失败了
### 报错信息

```
VM32973:5 Failed to load local font resource /fonts/icomoon.ttf?av4s6z-do-not-use-local-path-./app.wxss&15269&7  net::ERR_CACHE_MISS 

```

### 系统信息

SDKVersion："2.6.1"
model:"iPhone 6"
system:"iOS 10.0.1"
version:"6.6.3"
