### ISSUE TITLE
at-calendar 如何设置自定义样式？

### ISSUE THREAD

**Issue by agulado** [NervJS/taro-ui#544]
```javascript
/// .tsx

<AtCurtain
    isOpened={true}
    className='calendar-panel'    // 这里设置了幕帘的className
    closeBtnPosition='bottom'
    onClose={this.formCalendarClose.bind(this)}
>
    <AtCalendar
        currentDate={this.state.Tdate}
        onDayClick={this.formDayClick.bind(this)}
        className='calendar-box'    // 这里设置了日历的className
    />
</AtCurtain>
```

```less
/// .less

.calendar-panel {
  background: rgba(0, 0, 0, 1) !important; // 这个成功了
}
.calendar-box {
  background: rgb(255, 255, 255); // 这个没有
}
```

![1555808226738](https://user-images.githubusercontent.com/15799030/56464055-7913ae80-6413-11e9-84e4-5c03c1e4d926.jpg)

 - Taro 版本 [v1.2.2]
 - Taro UI 版本 [v.1.5.3]
 - 报错平台 [weapp]
