### ISSUE TITLE
AtRadio的label过长时不会自动换行

### ISSUE THREAD

**Issue by kennylbj** [NervJS/taro-ui#548]
**问题描述**

AtRadio的label过长时不会自动换行
**复现步骤**

```js
<AtRadio
   options={[
      { label: 'long long long long long long label', value: 'A',},
    ]}
/>
```
label不换行，且过长的文字无法显示。

**期望行为**

当label长度较长时，会自动换行。

**系统信息**

Taro UI 2.1.0

**Comment by kennylbj** [comment]
Fixed by:
```css
.at-radio {
  &__title {
    word-break: break-all;
  }
}
```
