### ISSUE TITLE
Taro UI AtIcon 组件引入第三方字体图标无效

### ISSUE THREAD

**Issue by FEhaoxinjie** [NervJS/taro-ui#647]
**问题描述**
Taro UI AtIcon 引入第三方字体图标类名重复
**复现步骤**

```js
// dev.js 
module.exports = {
  env: {
    NODE_ENV: '"development"'
  },
  defineConstants: {
  },
  weapp: {
    module: {
      postcss: {
        autoprefixer: {
          enable: true
        },
        // 小程序端样式引用本地资源内联配置
        url: {
          enable: true,
          config: {
            limit: 10240 // 文件大小限制
          }
        }
      }
    }
  },
  h5: {}
}

```

```js
// prod.js 
module.exports = {
  env: {
    NODE_ENV: '"development"'
  },
  defineConstants: {
  },
  weapp: {
    module: {
      postcss: {
        autoprefixer: {
          enable: true
        },
        // 小程序端样式引用本地资源内联配置
        url: {
          enable: true,
          config: {
            limit: 10240 // 文件大小限制
          }
        }
      }
    }
  },
  h5: {}
}

```

```css
@font-face {font-family: "iconfont";
  src: url('//at.alicdn.com/t/font_1251105_2uyex20h3x8.eot?t=1560937882718'); /* IE9 */
  src: url('//at.alicdn.com/t/font_1251105_2uyex20h3x8.eot?t=1560937882718#iefix') format('embedded-opentype'), /* IE6-IE8 */
  url('data:application/x-font-woff2;charset=utf-8;base64,d09GMgABAAAAAAMkAAsAAAAABuQAAALWAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHEIGVgCDBgqBNIFRATYCJAMMCwgABCAFhG0HUBsxBiMRZlPPJPuLA57MlXEDalRtqO20soeqt01MT9wUOH3ggexwwJPPELcIM+GS/z4evtbQ9/c2iC5RiBoACwTCo2qVq5AVquNZAgl9+z9nJZATJtuBLMljtfkjX8hvOX1pOlInnDpjp5O7NM+CzC4acUs4kUDvBcDQuUA3DsDRjWaRVF9YRcf/rd0Gj3e0FP3Ig2Omi/LGPF+4ZARWAk5wQN04Gtk/yAv6D2MXvMDXBGp1GxHLq9vHPJm9KRAP7925xiuEZZnlqoXKhpNZvNNMdXpjYN5Gvx9/p8IjqSjYO/dvr9z08aP1v8P8u00FCE2ynBPsHAVGkInLjemzTMGIhVq11V1aKQtpqditjMSGstL5h0cSRCW7uh4MoEziR6snzjQdUPrU1QWoTCpmcJGtb586O6rAzcvvFUS9ZBi6tH7c92ndRBDMHKSQmVgNNr1cP0SEXkQYBISuP7tRqfHTxNi90OoOcjIGhDqjUntBaIAw37bhhj/7qEgg8lPXWlw+z7VH2JDPp8ZxSwRAAgEsgM2nsbx33rtKQynzTIFGlh7/4b+x/+I2m256eVeHGXyaeNwoXMrC8Ey1BJP8T8nAoWzIbEuRNbEntryFyYnOBBRynxK2v9X36U33nA3VOjJIqnRBoVoPMmNHoEKdGahUbQ5qDVs7X6fNc6bINRjyAkBo9h6SRh+g0OwjMmO/QYVO/6FSc5hQ6zQ2N9bpi8dtQMZcsILiAm1Jk3JtEsS1n1ivQ855WUT/RV7aGKRRUs4dcEJeYs9yrDMRBYpphD14D4eBYGbqsJSoEZmf4lg1fSkqadQCZMwFKygu0JY0qWCyBJWf/8R6HXLuaKvz/yIv7fSQRskA5EE9DWp7lE+WY52JKFBMI+yBEwcnTTA3L+uwlKiZkJyfYjRODVVH22vHHyhiXdj1Zhi6qVtaPPqMa9NeVyranJKidcqy8EyDSz51oUnTAAAA') format('woff2'),
  url('//at.alicdn.com/t/font_1251105_2uyex20h3x8.woff?t=1560937882718') format('woff'),
  url('//at.alicdn.com/t/font_1251105_2uyex20h3x8.ttf?t=1560937882718') format('truetype'), /* chrome, firefox, opera, Safari, Android, iOS 4.2+ */
  url('//at.alicdn.com/t/font_1251105_2uyex20h3x8.svg?t=1560937882718#iconfont') format('svg'); /* iOS 4.1- */
}

.icon {
  font-family: "iconfont" !important;
  font-size: 16px;
  font-style: normal;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

.icon-search:before {
  content: "\e615";
}

.icon-arrow_bottom:before {
  content: "\e612";
}


```

```js
import Taro, { Component } from '@tarojs/taro'
import { AtIcon } from 'taro-ui'
import { View, Text } from '@tarojs/components'
import './index.scss'

class Filter extends Component {
    render() {
        return (
            <View className="filter">
                <View className="filter-header">
                    <View className="filter-btn">
                        城市
                    </View>
                    <View className="filter-btn">
                        职位
                       {/* 这样写是不能显示的 */}
                        <AtIcon 
                        prefixClass='icon'
                        value='arrow_bottom'
                        size='18'
                        color='#ccc' 
                        />
                    </View>
                    </View>
                </View>
            </View>
        )
    }
}
```

**期望行为**
类名正常

**报错信息**
![image](https://user-images.githubusercontent.com/26730557/59822129-4e37cf00-935e-11e9-9c32-2f7b294d49e3.png)
而且发现类名是重复的

**系统信息**
 Taro CLI 1.3.2 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm

 - Taro 版本 v1.3.2
 - Taro UI 版本 v2.2.1
 - 报错平台  weapp
