### ISSUE TITLE
对AtButton做样式覆盖失效

### ISSUE THREAD

**Issue by mdothy** [NervJS/taro-ui#66]
node:v10.4.0
Taro:v1.0.0-beta.26
Taro-UI: 1.2.1

样式覆盖
.at-button--primary{
  background: #157CF8;
  color:#fff;
}

在微信开发者工具中打开却并不生效
.at-button--primary {
background-color:#5c89e4;
color:#fff;
border:1PX solid #5c89e4;
}

**Comment by SzHeJason** [comment]
@mdothy 试了一下 应该是taro 对于组件的编译优先级有问题 可以给组件新增一个 `className` 样式来解决

```jsx
<AtButton type='primary' className='test'>主操作按钮</AtButton>
```

```scss
.test.at-button--primary {
  background: #157cf8;
  color: #fff;
}
```

如果需要全局改动 可以加一个 `!important` 的规则
