### ISSUE TITLE
AtInput placeholder 抖动

### ISSUE THREAD

**Issue by pssgo** [NervJS/taro-ui#74]
AtInput placeholder 在真机上会抖动 

### 重现步骤
```js
<View className='index'>
        <View className='search'>
          <AtInput placeholder="请输入要搜索的资源名称" className="input-search"/>
          <AtButton type='primary' size='small'>Biu~</AtButton>
        </View>
      </View>
```
```less
.search {
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 0 20px;
    border: 1px solid red;
    height: 100rpx;
    .at-input {
        line-height: 100rpx;
    }
    .at-button {
        margin-left: 40px !important;
    }
}

.input-search {
    border: 1px solid #ccc !important;
    padding: 10px 0 10px 30px !important;
    border-radius: 6666px;
    flex: 1 !important;
    width: auto !important; 
}
```

### 依赖的版本号
- Node 10.0
- Taro 1.0.1
- Taro-ui 1.2.1

### 预期结果
预期placeholder 不会抖动

### 实际结果
placeholder在 ios真机上 会抖动  安卓未测试
