### ISSUE TITLE
taro-ui 按钮关于 size 的问题

### ISSUE THREAD

**Issue by JakeXu** [NervJS/taro-ui#826]
**问题描述**
[问题描述：在页面中加入 taro-ui 的按钮组件, 设置 size 为 small, 得到的按钮效果就跟加了 full 一样]

**复现步骤**
[复现问题的步骤]
1. 初始化一个 taro 微信项目
2. 添加一个 size 为 small 的按钮
4. 得到的按钮部分样式如下:
```css
.at-button--small {
  padding: 0 16rpx;
  width: auto;
  min-width: 100rpx;
  max-width: 710rpx;
  height: 60rpx;
  font-size: 28rpx;
  line-height: 58rpx;
}
```

```js

<AtButton type='primary' size='small'>按钮文案</AtButton>

```

**期望行为**
[展示一个 small 的按钮]

**报错信息**

[无]

**系统信息**

 - 操作系统: [macOS 10.14.6]
 - Taro 版本 [e.g. v.1.3.20]
 - Node.js 版本 [12.12.0]
 - 报错平台 [weapp]

**补充信息**
[无]
