### ISSUE TITLE
小程序对应的页面背景色，怎么写？

### ISSUE THREAD

**Issue by bao-th** [NervJS/taro-ui#869]
**这个功能解决了什么问题？**

**你期望的功能是怎样的？**

**补充信息**

**Comment by Garfield550** [comment]
https://juejin.im/post/59eeec2451882546d71e8740
```css
page {
  background-color: #ffffff;
}
```
